[package]
name = "pomo"
version = "0.1.0"
edition = "2021"
description = "Timer pomodoro para waybar/eww (Omarchy/Hyprland)"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
dirs = "5"

[profile.release]
strip = true
opt-level = "z"
lto = true
